#! /bin/bash

magenta () { echo -e "\e[1m\e[35m$1\e[0m"; }
red () { echo -e "\e[1m\e[31m$1\e[0m"; }
green () { echo -e "\e[1m\e[32m$1\e[0m"; }
yellow () { echo -e "\e[1m\e[33m$1\e[0m"; }

magenta "Entering build Environment..."

docker run \
            -ti \
            --privileged \
            -v /etc/passwd:/etc/passwd \
            -v $HOME:$HOME \
            -u $(id -u ${USER}) \
            -w $HOME \
            yocto:2.7 \
            /bin/bash 